# Generated by Django 3.2.11 on 2022-04-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'verbose_name': 'habitación', 'verbose_name_plural': 'habitaciones'},
        ),
    ]
